### ISSUE TITLE
Survey Position Auto Populate

### ISSUE THREAD

**Issue by jordantkirby** [swift-nav/piksi_tools#180] opened 2015-10-14 03:50 UTC
It would be convenient to be able to auto-populate the surveyed positions from the position of the base station -- such as a simple button to grab the current position. I have difficulties copying the data from the solutions tab, even after pausing the position updates.

**Comment by switanis** [comment] 2016-05-26 16:07
Duplicate of #144. Closed.
https://github.com/swift-nav/piksi_tools/issues/144

**Closed by switanis** 2016-05-26 16:07 UTC
