### ISSUE TITLE
Allow users to choose location of saved logfiles in the console 

### ISSUE THREAD

**Issue by denniszollo** [swift-nav/piksi_tools#33] opened 2015-04-27 17:18 UTC
Command line argument with defaults for each platform
 filechooser and file breaking capability somewhere in console

We get this user feedback all the time -no one ever knows where the logfiles are

**Comment by denniszollo** [comment] 2015-06-01 17:02
We also need to choose download location of firmware artifacts.

**Comment by switanis** [comment] 2016-05-26 16:21
Duplicate of #150 and #63. Closed.

**Closed by switanis** 2016-05-26 16:21 UTC
